config/routes.rb
Rails.application.routes.draw do

  resources :api_configs do
    resources :lead
  end

  root 'api_configs#index'

end

app/models/api_config.rb
class ApiConfig < ActiveRecord::Base
  validates :username, :password, :security_token, :client_id, :client_secret, :presence => true
end

app/controllers/api_configs_controller.rb
class ApiConfigsController < ApplicationController
  before_action :set_api_config, only: [:show, :edit, :update, :destroy]

  # GET /api_configs
  # GET /api_configs.json
  def index
    @api_configs = ApiConfig.all
  end

  # GET /api_configs/1
  # GET /api_configs/1.json
  def show
  end

  # GET /api_configs/new
  def new
    @api_config = ApiConfig.new
  end

  # GET /api_configs/1/edit
  def edit
  end

  # POST /api_configs
  # POST /api_configs.json
  def create
    @api_config = ApiConfig.new(api_config_params)

    respond_to do |format|
      if @api_config.save
        format.html { redirect_to @api_config, notice: 'Api config was successfully created.' }
        format.json { render :show, status: :created, location: @api_config }
      else
        format.html { render :new }
        format.json { render json: @api_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /api_configs/1
  # PATCH/PUT /api_configs/1.json
  def update
    respond_to do |format|
      if @api_config.update(api_config_params)
        format.html { redirect_to @api_config, notice: 'Api config was successfully updated.' }
        format.json { render :show, status: :ok, location: @api_config }
      else
        format.html { render :edit }
        format.json { render json: @api_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /api_configs/1
  # DELETE /api_configs/1.json
  def destroy
    @api_config.destroy
    respond_to do |format|
      format.html { redirect_to api_configs_url, notice: 'Api config was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_api_config
      @api_config = ApiConfig.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def api_config_params
      params.require(:api_config).permit(:username, :password, :security_token, :client_id, :client_secret)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lead_controller.rb
class LeadController < ApplicationController
  before_action :set_lead, only: [:show, :edit, :update, :destroy]
  
  def index
    @api_config = ApiConfig.find(params[:api_config_id])
    attrs = {
      :username => @api_config.username,
      :password => @api_config.password,
      :security_token => @api_config.security_token,
      :client_id => @api_config.client_id,
      :client_secret => @api_config.client_secret
     }
    @leads = RdApi::Lead.new(attrs).all
  end

  def new
    @api_config = ApiConfig.find(params[:api_config_id])
  end

  def create
    @api_config = ApiConfig.find(params[:api_config_id])
    attrs = {
      :username => @api_config.username,
      :password => @api_config.password,
      :security_token => @api_config.security_token,
      :client_id => @api_config.client_id,
      :client_secret => @api_config.client_secret
     }
    @new_id = RdApi::Lead.new(attrs).create(lead_params[:Title], lead_params[:Phone], lead_params[:Company], lead_params[:Email], lead_params[:FirstName], lead_params[:LastName])
    flash[:notice] = 'Lead helper was successfully created.'
	redirect_to api_config_lead_path(@api_config, @new_id)
  end

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lead
      @api_config = ApiConfig.find(params[:api_config_id])
      attrs = {
        :username => @api_config.username,
        :password => @api_config.password,
        :security_token => @api_config.security_token,
        :client_id => @api_config.client_id,
        :client_secret => @api_config.client_secret
       }
      @lead = RdApi::Lead.new(attrs).find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lead_params
      params.permit(:api_config_id, :Title, :Phone, :Company, :Email, :FirstName, :LastName, :utf8, :authenticity_token, :commit)
    end
end

app/helpers/api_configs_helper.rb
module ApiConfigsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lead_helper.rb
module LeadHelper
end

app/helpers/lead_helpers_helper.rb
module LeadHelpersHelper
end

app/views/api_configs/_form.html.erb
<%= form_for(@api_config) do |f| %>
  <% if @api_config.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@api_config.errors.count, "error") %> prohibited this api_config from being saved:</h2>

      <ul>
      <% @api_config.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div id="control_panel" class="col-md-3">
      <div class="field">
        <%= f.label :username %><br>
        <%= f.text_field :username %>
      </div>
      <div class="field">
        <%= f.label :password %><br>
        <%= f.password_field :password %>
      </div>
      <div class="field">
        <%= f.label :security_token %><br>
        <%= f.text_field :security_token %>
      </div>
      <div class="field">
        <%= f.label :client_id %><br>
        <%= f.text_field :client_id %>
      </div>
      <div class="field">
        <%= f.label :client_secret %><br>
        <%= f.text_field :client_secret %>
      </div>
      <div class="actions">
        <%= f.submit class: "btn btn-primary btn-block" %>
      </div>
    </div>
  </div>
<% end %>

app/views/api_configs/edit.html.erb
<h1>Editing api_config</h1>

<%= render 'form' %>

<%= link_to 'Show', @api_config %> |
<%= link_to 'Back', api_configs_path %>

app/views/api_configs/index.html.erb
<h1 class="page-header">Listing api_configs</h1>

<div class="well">
<%= link_to 'New Api config', new_api_config_path, class: "btn btn-primary" %>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @api_configs.each do |api_config| %>
      <tr>
        <td><%= api_config.username %></td>
        <td><%= link_to 'Leads', api_config_lead_index_path(api_config) %></td>
        <td><%= link_to 'Show', api_config %></td>
        <td><%= link_to 'Edit', edit_api_config_path(api_config) %></td>
        <td><%= link_to 'Destroy', api_config, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/api_configs/new.html.erb
<h1>New api_config</h1>

<%= render 'form' %>

<%= link_to 'Back', api_configs_path %>

app/views/api_configs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @api_config.username %>
</p>

<%= link_to 'Edit', edit_api_config_path(@api_config) %> |
<%= link_to 'Back', api_configs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RdApp</title>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css", media: "all" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lead/_form.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div id="control_panel" class="col-md-3">
    <%= form_tag(api_config_lead_index_path) do -%>
      <div class="field">
        <%= label_tag :Title %><br>
        <%= text_field_tag :Title %>
      </div>
      <div class="field">
        <%= label_tag :Phone %><br>
        <%= text_field_tag :Phone %>
      </div>
      <div class="field">
        <%= label_tag :Company %><br>
        <%= text_field_tag :Company %>
      </div>
      <div class="field">
        <%= label_tag :Email %><br>
        <%= text_field_tag :Email %>
      </div>
      <div class="field">
        <%= label_tag :FirstName %><br>
        <%= text_field_tag :FirstName %>
      </div>
      <div class="field">
        <%= label_tag :LastName %><br>
        <%= text_field_tag :LastName%>
      </div>
      <div class="actions">
        <%= submit_tag 'Save', class: "btn btn-primary btn-block" %>
      </div>
    <% end %>
  </div>
</div>

app/views/lead/edit.html.erb
<h1 class="page-header">Editing lead_helper</h1>

<%= render 'form' %>

<%= link_to 'Show', @lead_helper %> |
<%= link_to 'Back', lead_helpers_path %>

app/views/lead/index.html.erb
<h1 class="page-header">Listing leads</h1>

<div class="well">
<%= link_to 'New Lead', new_api_config_lead_path(@api_config), class: "btn btn-primary"  %>
</div>
<br>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Phone</th>
      <th>Company</th>
      <th>Email</th>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leads.each do |lead| %>
      <tr>
        <td><%= lead.Title %></td>
        <td><%= lead.Phone %></td>
        <td><%= lead.Company %></td>
        <td><%= lead.Email %></td>
        <td><%= lead.FirstName %></td>
        <td><%= lead.LastName %></td>
        <td><%= link_to 'Show', api_config_lead_path(@api_config, lead.Id) %></td>
        <td><%= link_to 'Edit', edit_api_config_lead_path(@api_config, lead.Id) %></td>
        <td><%= link_to 'Destroy', lead, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/lead/new.html.erb
<h1 class="page-header">New lead_helper</h1>

<%= render 'form' %>

<%= link_to 'Back', api_config_lead_index_path(@api_config) %>

app/views/lead/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @lead.Title %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @lead.Phone %>
</p>

<p>
  <strong>Company:</strong>
  <%= @lead.Company %>
</p>

<p>
  <strong>Email,:</strong>
  <%= @lead.Email %>
</p>

<p>
  <strong>First name:</strong>
  <%= @lead.FirstName %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @lead.LastName %>
</p>

<%= link_to 'Edit', edit_api_config_lead_path(@api_config, @lead) %> |
<%= link_to 'Back', api_config_lead_index_path(@api_config) %>